spring.application.name=Entreprise-Apps-Hisham.Boussof

# H2 In-Memory Database Configuratie
spring.datasource.url=jdbc:h2:mem:ngodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Mailtrap Configuratie (Nu met jouw correcte gegevens)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=42292d512a60ad
spring.mail.password=cb62463eef25bb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true